# Generated by Django 2.2.17 on 2021-09-10 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='deadlift',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='militarypress',
            field=models.PositiveIntegerField(1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='pullups',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='training',
            name='bench',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='squats',
            field=models.PositiveIntegerField(),
        ),
    ]
