# Generated by Django 2.2.17 on 2021-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20210910_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='bench',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='deadlift',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='militarypress',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='pullups',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='squats',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
